services:
    # Local development database (hardcoded credentials for simplicity)
    db:
        container_name: invoice-db
        image: mysql:8.0.33
        platform: linux/arm64/v8
        command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0 --skip-name-resolve
        ports:
            - "3306:3306"
        volumes:
            - "db_app:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: app_db
            MYSQL_USER: app_user
            MYSQL_PASSWORD: "password"
        networks:
            - symfony_app
        profiles:
            - local

    php:
        container_name: invoice-php
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - symfony_app_var:/var/www/symfony/var
            - symfony_app_vendor:/var/www/symfony/vendor
        expose:
            - 80
        networks:
            - coolify
            - symfony_app
        environment:
            APP_ENV: ${APP_ENV:-prod}
            DATABASE_URL: ${DATABASE_URL}
        labels:
            - "coolify.managed=true"
            - "coolify.port=80"
            - "traefik.enable=true"
            - "traefik.http.routers.php.rule=Host(`zcpnf45f6v9f8vu3lqt9iwqb.89.168.97.22.sslip.io`)"
            - "traefik.http.routers.php.entrypoints=http"
            - "traefik.http.services.php.loadbalancer.server.port=80"
            - "traefik.docker.network=coolify"

volumes:
    symfony_app_var:
    symfony_app_vendor:
    db_app:

networks:
    symfony_app:
    coolify:
        external: true
