name: CI/CD Pipeline

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.2'

            - name: Install dependencies
              env:
                  APP_ENV: prod
              run: composer install --no-dev --optimize-autoloader

            - name: Deploy to server
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  SERVER_HOST: ${{ secrets.SERVER_HOST }}
                  SERVER_USER: ${{ secrets.SERVER_USER }}
                  APP_ENV: prod
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts
                  rsync -avz --exclude='.git' ./ $SERVER_USER@$SERVER_HOST:/var/www/admin
                  ssh $SERVER_USER@$SERVER_HOST "cd /var/www/admin/.docker && APP_ENV=prod docker compose up -d"
                  ssh $SERVER_USER@$SERVER_HOST "docker exec -i admin-php-1 bash -c 'APP_ENV=prod composer install --no-dev --optimize-autoloader'"
                  ssh $SERVER_USER@$SERVER_HOST "docker exec -i admin-php-1 bash -c 'bin/console doctrine:migrations:migrate --no-interaction'"